server:
    port: 8000

spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            routes:
                -   id: topic-service
                    uri: lb://topic-service
                    predicates:
                        - Path=/ui/v1/topics/**
                    filters:
                        - AuthFilter

                -   id: tag-service
                    uri: lb://tag-service
                    predicates:
                        - Path=/ui/v1/tags/**, /api/v1/tags/**
                    filters:
                        - AuthFilter

                -   id: tweet-service
                    uri: lb://tweet-service
                    predicates:
                        - Path=/ui/v1/tweets/**, /api/v1/tweets/**
                    filters:
                        - AuthFilter

                -   id: user-service
                    uri: lb://user-service
                    predicates:
                        - Path=/ui/v1/user/**, /api/v1/user/**, /api/v1/auth/user/**
                    filters:
                        - AuthFilter

                -   id: lists-service
                    uri: lb://lists-service
                    predicates:
                        - Path=/ui/v1/lists/**
                    filters:
                        - AuthFilter

                -   id: chat-service
                    uri: lb://chat-service
                    predicates:
                        - Path=/ui/v1/chat/**
                    filters:
                        - AuthFilter

                -   id: notification-service
                    uri: lb://notification-service
                    predicates:
                        - Path=/ui/v1/notification/**
                    filters:
                        - AuthFilter

    zipkin:
        base-url: http://localhost:9411

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true
